# config/database.yml
#
# you must create the users and database with postgres
# before the connection will work
#
#% createuser -P ige_aa_test_user (then enter the password 'test_ige_aa' at the prompt.)
#% createdb ige_aa_test_db -O ige_aa_test_user
#
# to drop the database for any reason
#% dropdb ige_aa_test_db
#
#% createuser -P ige_aa_dev_user (then enter the password 'dev_ige_aa' at the prompt.)
#% createdb ige_aa_dev_db -O ige_aa_dev_user
#
# to drop the database for any reason
#% dropdb ige_aa_dev_db
#
# If the DB is not running check here
# https://gist.github.com/demimismo/3359506

test:
  adapter: postgresql
  database: ige_aa_test_db
  username: ige_aa_test_user
  password: test_ige_aa
  host: localhost
  port: 5432

development:
  adapter: postgresql
  database: ige_aa_dev_db
  username: ige_aa_dev_user
  password: dev_ige_aa
  host: localhost
  port: 5432
